name: Update GitHub Profile

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Stats
        uses: stats-organization/github-readme-stats-action@main
        with:
          card: stats
          username: yadav-shubh
          path: profile/stats.svg
          options: show_icons=true&theme=tokyonight

      - name: Generate Top Languages
        uses: stats-organization/github-readme-stats-action@main
        with:
          card: top-langs
          username: yadav-shubh
          path: profile/top-langs.svg
          options: layout=compact&theme=tokyonight

      - name: Generate Contribution Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: yadav-shubh
          outputs: |
            profile/github-snake.svg
            profile/github-snake-dark.svg?palette=github-dark

      - name: Commit generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/*.svg

          git commit -m "Update GitHub profile stats" || exit 0

          git push
